export interface Holiday {
  name: string;
  name_local: string;
  language: string;
  country: string;
  location: string;
  type: string;
  date: string;
  date_year: string;
  date_month: string;
  date_day: string;
  week_day: string;
}

export const sweden2022 = [
  {
    name: "New Year's Day",
    name_local: "",
    language: "",
    description: "",
    country: "SE",
    location: "Sweden",
    type: "National",
    date: "01/01/2022",
    date_year: "2022",
    date_month: "01",
    date_day: "01",
    week_day: "Saturday",
  },
  {
    name: "Epiphany",
    name_local: "",
    language: "",
    description: "",
    country: "SE",
    location: "Sweden",
    type: "National",
    date: "01/06/2022",
    date_year: "2022",
    date_month: "01",
    date_day: "06",
    week_day: "Thursday",
  },
  {
    name: "Good Friday",
    name_local: "",
    language: "",
    description: "",
    country: "SE",
    location: "Sweden",
    type: "National",
    date: "04/15/2022",
    date_year: "2022",
    date_month: "04",
    date_day: "15",
    week_day: "Friday",
  },
  {
    name: "Holy Saturday",
    name_local: "",
    language: "",
    description: "",
    country: "SE",
    location: "Sweden",
    type: "Local holiday",
    date: "04/16/2022",
    date_year: "2022",
    date_month: "04",
    date_day: "16",
    week_day: "Saturday",
  },
  {
    name: "Easter Sunday",
    name_local: "",
    language: "",
    description: "",
    country: "SE",
    location: "Sweden",
    type: "National",
    date: "04/17/2022",
    date_year: "2022",
    date_month: "04",
    date_day: "17",
    week_day: "Sunday",
  },
  {
    name: "Easter Monday",
    name_local: "",
    language: "",
    description: "",
    country: "SE",
    location: "Sweden",
    type: "National",
    date: "04/18/2022",
    date_year: "2022",
    date_month: "04",
    date_day: "18",
    week_day: "Monday",
  },
  {
    name: "May 1st",
    name_local: "",
    language: "",
    description: "",
    country: "SE",
    location: "Sweden",
    type: "National",
    date: "05/01/2022",
    date_year: "2022",
    date_month: "05",
    date_day: "01",
    week_day: "Sunday",
  },
  {
    name: "Ascension Day",
    name_local: "",
    language: "",
    description: "",
    country: "SE",
    location: "Sweden",
    type: "National",
    date: "05/26/2022",
    date_year: "2022",
    date_month: "05",
    date_day: "26",
    week_day: "Thursday",
  },
  {
    name: "Pentecost Eve",
    name_local: "",
    language: "",
    description: "",
    country: "SE",
    location: "Sweden",
    type: "Local holiday",
    date: "06/04/2022",
    date_year: "2022",
    date_month: "06",
    date_day: "04",
    week_day: "Saturday",
  },
  {
    name: "Whit Sunday",
    name_local: "",
    language: "",
    description: "",
    country: "SE",
    location: "Sweden",
    type: "National",
    date: "06/05/2022",
    date_year: "2022",
    date_month: "06",
    date_day: "05",
    week_day: "Sunday",
  },
  {
    name: "National day",
    name_local: "",
    language: "",
    description: "",
    country: "SE",
    location: "Sweden",
    type: "National",
    date: "06/06/2022",
    date_year: "2022",
    date_month: "06",
    date_day: "06",
    week_day: "Monday",
  },
  {
    name: "Midsummer Eve",
    name_local: "",
    language: "",
    description: "",
    country: "SE",
    location: "Sweden",
    type: "Local holiday",
    date: "06/24/2022",
    date_year: "2022",
    date_month: "06",
    date_day: "24",
    week_day: "Friday",
  },
  {
    name: "Midsummer Day",
    name_local: "",
    language: "",
    description: "",
    country: "SE",
    location: "Sweden",
    type: "National",
    date: "06/25/2022",
    date_year: "2022",
    date_month: "06",
    date_day: "25",
    week_day: "Saturday",
  },
  {
    name: "All Saints' Day",
    name_local: "",
    language: "",
    description: "",
    country: "SE",
    location: "Sweden",
    type: "National",
    date: "11/05/2022",
    date_year: "2022",
    date_month: "11",
    date_day: "05",
    week_day: "Saturday",
  },
  {
    name: "Christmas Eve",
    name_local: "",
    language: "",
    description: "",
    country: "SE",
    location: "Sweden",
    type: "Local holiday",
    date: "12/24/2022",
    date_year: "2022",
    date_month: "12",
    date_day: "24",
    week_day: "Saturday",
  },
  {
    name: "Christmas Day",
    name_local: "",
    language: "",
    description: "",
    country: "SE",
    location: "Sweden",
    type: "National",
    date: "12/25/2022",
    date_year: "2022",
    date_month: "12",
    date_day: "25",
    week_day: "Sunday",
  },
  {
    name: "Boxing Day",
    name_local: "",
    language: "",
    description: "",
    country: "SE",
    location: "Sweden",
    type: "National",
    date: "12/26/2022",
    date_year: "2022",
    date_month: "12",
    date_day: "26",
    week_day: "Monday",
  },
  {
    name: "New Year's Eve",
    name_local: "",
    language: "",
    description: "",
    country: "SE",
    location: "Sweden",
    type: "Local holiday",
    date: "12/31/2022",
    date_year: "2022",
    date_month: "12",
    date_day: "31",
    week_day: "Saturday",
  },
];
